### ISSUE TITLE
qmk ? 

### ISSUE THREAD

**Issue by lazy-unicorn** [wizarddata/Blue-Wizard-Mod#1]
sup fellow kinesis user - 

is there a good reason why you make your life harder then necessary ? 

nordic is cool and all but there are easyer ways out of that hell 

uart/spi integration works with like any arm mcu or even smaller/cheaper ones
https://beta.docs.qmk.fm/using-qmk/hardware-features/feature_bluetooth
if you design your power logic / regular mcu ( say STM32F303 ) - all it takes to make the board bt capeable is to connect the bt modul via spi/uart to the main mcu and "bob is your uncle" you even find some example firmware with bt in qmk repo  

or 

https://github.com/sysdevmike/KinesisBLE - works with your nordic soc

**Comment by wizarddata** [comment]
Sup dawg.

I spent some time with the QMK implementation of bluetooth a while back, worked jut fine but the battery life was much shorter than I would like (on the order of 5 days on a ~2000mah 18650). 

I went with BlueMicro because it is a more widely used bluetooth firmware than the kinesis specific KinesisBLE project. My thought was it would lead to more features down the road as development continued. Even with the KinesisBLE project, it would require an Adafruit feather module and an MCP23S17 I/O expander without the same porting I'm doing here. That is, unless I'm missing something, which is entirely possible.

**Comment by lazy-unicorn** [comment]
valid - did not think about that - battery may be extendable if reducing the scanning rate / frequency of the chip

if we talk about features qmk is the clear winner here 
+ more features also require more mcu cycles = more power drain.

i have a look in the firmware you got already and see what i can do

**Comment by wizarddata** [comment]
I'd definitely appreciate the help. Where I'm at is (thanks to a lot of help from the adafruit forum and bluemicro discord) I've got a new bootloader to relocate the LED pins, a customized BSP to account for my not including a LF oscillator, and a procedure to correct for some work that is usually done by adafruit-nrfutil when programmed over serial. The test code BlueMicroHID_tester works perfectly but the firmware I'm building for my board stops advertising after 1-2 seconds.

**Comment by wizarddata** [comment]
Got the booting issues sorted and even got to the point where I could use all the IO I needed, then ran out of dynamic memory. This project is going to get upgraded to a 840.
